create table cursos (

    id bigint generated by default as identity primary key,
    nome varchar(150) not null,
    categoria varchar(100) not null

);

create table usuario (

     id bigint generated by default as identity primary key,
     nome varchar(200) not null,
     email varchar(200) not null UNIQUE,
     senha varchar(255) not null

);

create table topico (

    id bigint generated by default as identity primary key,
    titulo varchar(100) not null,
    mensagem  TEXT not null,
    data_criacao TIMESTAMP not null,
    status varchar(100) not null,

    usuario_id INTEGER not null,
    curso_id INTEGER not null,

    CONSTRAINT fk_topico_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_topico_curso FOREIGN KEY (curso_id) REFERENCES cursos(id)

);

create table resposta (

    id bigint generated by default as identity primary key,
    mensagem  TEXT not null,
    data_criacao TIMESTAMP not null,

    usuario_id INTEGER not null,
    topico_id INTEGER not null,

    CONSTRAINT fk_resposta_topico FOREIGN KEY (topico_id) references topico(id),
    CONSTRAINT fk_resposta_usuario FOREIGN KEY (usuario_id) references usuario(id)

);

create table perfil (

    id bigint generated by default as identity primary key,
    nome varchar(200) not null

);

create table usuario_perfil (

    usuario_id INTEGER not null,
    perfil_id INTEGER not null,

    primary key (usuario_id, perfil_id),

    CONSTRAINT fk_up_usuario FOREIGN KEY (usuario_id) references usuario(id),
    CONSTRAINT fk_up_perfil FOREIGN KEY (perfil_id) references perfil(id)

);